include("analytical/currentsheet.jl")
include("analytical/dipole.jl")
include("analytical/wire.jl")
include("analytical/mirror.jl")
include("analytical/tokamak.jl")
include("analytical/zpinch.jl")
include("analytical/uniform.jl")
include("analytical/magnetosphere.jl")
