"""
    BiotSavart{BC <: AbstractBoundary} <: AbstractSolver

Solver that uses the Biot-Savart law to compute the magnetic field.
The boundary condition `BC` controls how sources outside the physical domain
are treated (e.g., image sources for a conducting wall).

The default constructor `BiotSavart()` uses `OpenBoundary`.
"""
struct BiotSavart{BC <: AbstractBoundary} <: AbstractSolver
    bc::BC
end

BiotSavart() = BiotSavart(OpenBoundary())

# ---------------------------------------------------------------------------
# Core kernel (open / free-space)
# ---------------------------------------------------------------------------

"""
    solve(solver::BiotSavart, source::Wire, r) where T

Compute the magnetic field at position `r` generated by a `Wire` source using the Biot-Savart law.
It assumes the wire is composed of straight segments between the points.

The magnetic field for a finite wire segment is calculated using the algebraic form:
```math
\\mathbf{B} = \\frac{\\mu_0 I}{4\\pi} \\frac{\\mathbf{dl} \\times \\mathbf{a}}{|\\mathbf{dl} \\times \\mathbf{a}|^2} \\left( \\frac{\\mathbf{dl} \\cdot \\mathbf{a}}{|\\mathbf{a}|} - \\frac{\\mathbf{dl} \\cdot \\mathbf{b}}{|\\mathbf{b}|} \\right)
```
where:
- \$\\mathbf{a} = \\mathbf{r} - \\mathbf{r}_{start}\$ is the vector from the start of the segment to the observation point.
- \$\\mathbf{b} = \\mathbf{r} - \\mathbf{r}_{end}\$ is the vector from the end of the segment to the observation point.
- \$\\mathbf{dl} = \\mathbf{r}_{end} - \\mathbf{r}_{start}\$ is the segment vector.
"""
function solve(::BiotSavart, source::Wire{T}, r::SVector{3, T}) where {T}
    B = @SVector zeros(T, 3)
    points = source.points
    I = source.current

    @inbounds for i in 1:(length(points) - 1)
        r1 = points[i]
        r2 = points[i + 1]

        # Vectors from r to the start and end of the segment
        a = r - r1
        b = r - r2
        dl = r2 - r1 # Segment vector

        cross_prod = cross(dl, a)
        cross_sq = dot(cross_prod, cross_prod)

        if cross_sq < 1.0e-20 # Check for singularity (point on line)
            continue
        end

        term = (dot(dl, a) / norm(a) - dot(dl, b) / norm(b))
        B += (T(μ0_4π) * I) * (cross_prod / cross_sq) * term
    end

    return B
end

# Helper to support arbitrary location input
function solve(solver::BiotSavart, source::Wire{T}, r) where {T}
    return solve(solver, source, SVector{3, T}(r))
end

# ---------------------------------------------------------------------------
# SurfaceCurrentMesh kernel (shared by all BC variants)
# ---------------------------------------------------------------------------

"""
    solve(solver::BiotSavart, mesh::SurfaceCurrentMesh, r)

Compute the magnetic field at `r` from a `SurfaceCurrentMesh` using the
far-field Biot-Savart approximation for each patch:

    dB(r) = (μ₀/4π) * Aᵢ * (Kᵢ × Rᵢ) / |Rᵢ|³
"""
function solve(
        ::BiotSavart, mesh::SurfaceCurrentMesh{T},
        r::SVector{3, T}
    ) where {T}
    B = @SVector zeros(T, 3)
    @inbounds for i in eachindex(mesh.centers)
        R = r - mesh.centers[i]
        R_norm = norm(R)
        R_norm < 1.0e-20 && continue
        K_vec = mesh.K[i][1] * mesh.tangents1[i] + mesh.K[i][2] * mesh.tangents2[i]
        B += (T(μ0_4π) * mesh.areas[i] / R_norm^3) * cross(K_vec, R)
    end
    return B
end

function solve(solver::BiotSavart, mesh::SurfaceCurrentMesh{T}, r) where {T}
    return solve(solver, mesh, SVector{3, T}(r))
end

# ---------------------------------------------------------------------------
# OpenBoundary (default) — no modification
# ---------------------------------------------------------------------------

# Already handled by the generic methods above; the type parameter is consumed
# but no extra work is done.

# ---------------------------------------------------------------------------
# Source-transformation helpers
# ---------------------------------------------------------------------------

"""
    image_source(source::Wire, bc::ConductingWall) -> Wire

Return the image `Wire` of `source` reflected across the planar conducting wall
defined by `bc`.  The image current is negated so that the tangential magnetic
field vanishes at the wall surface.
"""
function image_source(source::Wire{T}, bc::ConductingWall) where {T}
    ax = bc.axis
    wall = T(bc.position)
    reflected = map(source.points) do p
        delta = p[ax] - wall
        coords = ntuple(i -> i == ax ? wall - delta : p[i], 3)
        SVector{3, T}(coords)
    end
    return Wire{T}(reflected, -source.current)
end

"""
    periodic_sources(source::Wire, bc::PeriodicBoundary; nreplica=1) -> Vector{Wire}

Return all periodic image `Wire` sources of `source` within ±`nreplica` periods
in every direction defined by `bc.period`.  The original source is included.
"""
function periodic_sources(
        source::Wire{T}, bc::PeriodicBoundary;
        nreplica::Int = 1
    ) where {T}
    period = SVector{3, T}(bc.period)
    images = Wire{T}[]
    for ix in -nreplica:nreplica, iy in -nreplica:nreplica, iz in -nreplica:nreplica
        shift = SVector{3, T}(ix * period[1], iy * period[2], iz * period[3])
        shifted = map(p -> p + shift, source.points)
        push!(images, Wire{T}(shifted, source.current))
    end
    return images
end

# ---------------------------------------------------------------------------
# ConductingWall — method of images
# ---------------------------------------------------------------------------

function solve(
        solver::BiotSavart{ConductingWall}, source::Wire{T},
        r::SVector{3, T}
    ) where {T}
    B_direct = solve(BiotSavart(), source, r)
    img = image_source(source, solver.bc)
    B_image = solve(BiotSavart(), img, r)
    return B_direct + B_image
end

function solve(solver::BiotSavart{ConductingWall}, source::Wire{T}, r) where {T}
    return solve(solver, source, SVector{3, T}(r))
end

# ---------------------------------------------------------------------------
# PeriodicBoundary — source replication
# ---------------------------------------------------------------------------

function solve(
        solver::BiotSavart{PeriodicBoundary}, source::Wire{T},
        r::SVector{3, T}; nreplica::Int = 1
    ) where {T}
    images = periodic_sources(source, solver.bc; nreplica)
    B = @SVector zeros(T, 3)
    for img in images
        B += solve(BiotSavart(), img, r)
    end
    return B
end

function solve(
        solver::BiotSavart{PeriodicBoundary}, source::Wire{T}, r;
        nreplica::Int = 1
    ) where {T}
    return solve(solver, source, SVector{3, T}(r); nreplica)
end

# ---------------------------------------------------------------------------
# PrescribedBoundary — add background field
# ---------------------------------------------------------------------------

function solve(
        solver::BiotSavart{<:PrescribedBoundary}, source::Wire{T},
        r::SVector{3, T}
    ) where {T}
    B_source = solve(BiotSavart(), source, r)
    B_bg = SVector{3, T}(solver.bc.field_func(r))
    return B_source + B_bg
end

function solve(solver::BiotSavart{<:PrescribedBoundary}, source::Wire{T}, r) where {T}
    return solve(solver, source, SVector{3, T}(r))
end

# ---------------------------------------------------------------------------
# ConductingSphere — numerical BEM
# ---------------------------------------------------------------------------

"""
    sphere_mesh(bc::ConductingSphere) -> (centers, normals, tangents1, tangents2, areas)

Build a latitude-longitude patch mesh for the conducting sphere.
"""
function sphere_mesh(bc::ConductingSphere)
    T = Float64
    nθ, nφ = bc.n_theta, bc.n_phi
    N = nθ * nφ
    centers = Vector{SVector{3, T}}(undef, N)
    normals = Vector{SVector{3, T}}(undef, N)
    tangents1 = Vector{SVector{3, T}}(undef, N)
    tangents2 = Vector{SVector{3, T}}(undef, N)
    areas = Vector{T}(undef, N)

    dθ = π / nθ
    dφ = 2π / nφ
    R = bc.radius

    idx = 1
    for iθ in 1:nθ
        θ = (iθ - 0.5) * dθ
        sinθ, cosθ = sincos(θ)
        for iφ in 1:nφ
            φ = (iφ - 0.5) * dφ
            sinφ, cosφ = sincos(φ)

            n̂ = SVector{3, T}(sinθ * cosφ, sinθ * sinφ, cosθ)
            centers[idx] = bc.center + R * n̂
            normals[idx] = n̂
            tangents1[idx] = SVector{3, T}(cosθ * cosφ, cosθ * sinφ, -sinθ) # θ̂
            tangents2[idx] = SVector{3, T}(-sinφ, cosφ, zero(T))              # φ̂
            areas[idx] = R^2 * sinθ * dθ * dφ
            idx += 1
        end
    end
    return centers, normals, tangents1, tangents2, areas
end

"""
    compute_surface_current(bc::ConductingSphere, source::Wire) -> SurfaceCurrentMesh

Solve the BEM linear system for the induced surface current **K** on the
perfectly-conducting sphere defined by `bc` that cancels the normal component
of the incident field from `source`.

The incident field is computed with the free-space `BiotSavart` kernel.
"""
function compute_surface_current(bc::ConductingSphere, source::Wire{T}) where {T}
    centers, normals, tangents1, tangents2, areas = sphere_mesh(bc)
    N = length(centers)

    bare = BiotSavart()

    # Incident normal field at each patch centre
    b = Vector{T}(undef, N)
    for i in 1:N
        B_inc = solve(bare, source, centers[i])
        b[i] = -dot(normals[i], B_inc)
    end

    # Influence matrix M (N × 2N): M[i, 2j-1] = n̂ᵢ · dBⱼ(t̂1), M[i, 2j] = n̂ᵢ · dBⱼ(t̂2)
    M = zeros(T, N, 2N)
    for j in 1:N
        Aj = T(areas[j])
        for i in 1:N
            i == j && continue   # self-term regularized to zero
            R = centers[i] - centers[j]
            R_norm = norm(R)
            R_norm < 1.0e-20 && continue
            pre = T(μ0_4π) * Aj / R_norm^3
            for (k, t̂) in enumerate((tangents1[j], tangents2[j]))
                dB_n = dot(normals[i], pre * cross(t̂, R))
                M[i, 2j - 2 + k] = dB_n
            end
        end
    end

    # Minimum-norm least-squares solve (underdetermined system)
    x = M \ b

    K = [SVector{2, T}(x[2j - 1], x[2j]) for j in 1:N]
    return SurfaceCurrentMesh{T}(
        centers, normals, tangents1, tangents2,
        Vector{T}(areas), K
    )
end

function solve(
        solver::BiotSavart{ConductingSphere}, source::Wire{T},
        r::SVector{3, T}
    ) where {T}
    mesh = compute_surface_current(solver.bc, source)
    return solve(BiotSavart(), source, r) + solve(BiotSavart(), mesh, r)
end

function solve(solver::BiotSavart{ConductingSphere}, source::Wire{T}, r) where {T}
    return solve(solver, source, SVector{3, T}(r))
end
