"""
    BiotSavart <: AbstractSolver

Solver that uses the Biot-Savart law to compute the magnetic field.
"""
struct BiotSavart <: AbstractSolver end

"""
    solve(solver::BiotSavart, source::Wire, r::SVector{3, T}) where T

Compute the magnetic field at position `r` generated by a `Wire` source using the Biot-Savart law.
It assumes the wire is composed of straight segments between the points.

The magnetic field for a finite wire segment is calculated using the algebraic form:
```math
\\mathbf{B} = \\frac{\\mu_0 I}{4\\pi} \\frac{\\mathbf{dl} \\times \\mathbf{a}}{|\\mathbf{dl} \\times \\mathbf{a}|^2} \\left( \\frac{\\mathbf{dl} \\cdot \\mathbf{a}}{|\\mathbf{a}|} - \\frac{\\mathbf{dl} \\cdot \\mathbf{b}}{|\\mathbf{b}|} \\right)
```
where:
- \$\\mathbf{a} = \\mathbf{r} - \\mathbf{r}_{start}\$ is the vector from the start of the segment to the observation point.
- \$\\mathbf{b} = \\mathbf{r} - \\mathbf{r}_{end}\$ is the vector from the end of the segment to the observation point.
- \$\\mathbf{dl} = \\mathbf{r}_{end} - \\mathbf{r}_{start}\$ is the segment vector.
"""
function solve(::BiotSavart, source::Wire{T}, r::SVector{3, T}) where {T}
    B = @SVector zeros(T, 3)
    points = source.points
    I = source.current

    for i in 1:(length(points) - 1)
        r1 = points[i]
        r2 = points[i + 1]

        # Vectors from r to the start and end of the segment
        a = r - r1
        b = r - r2
        dl = r2 - r1 # Segment vector

        cross_prod = cross(dl, a)
        cross_sq = dot(cross_prod, cross_prod)

        if cross_sq < 1.0e-20 # Check for singularity (point on line)
            continue
        end

        term = (dot(dl, a) / norm(a) - dot(dl, b) / norm(b))
        B += (T(μ0_4π) * I) * (cross_prod / cross_sq) * term
    end

    return B
end

# Helper to support arbitrary vector input
function solve(solver::BiotSavart, source::AbstractCurrentSource, r::AbstractVector)
    return solve(solver, source, SVector{3}(r))
end
