"""
    VectorPotential{BC <: AbstractBoundary} <: AbstractSolver

Solver that computes the magnetic vector potential `A`.
The default constructor `VectorPotential()` uses `OpenBoundary`.
"""
struct VectorPotential{BC <: AbstractBoundary} <: AbstractSolver
    bc::BC
end

VectorPotential() = VectorPotential(OpenBoundary())

"""
    solve(solver::VectorPotential, source::Wire, r) where T

Compute the vector potential A at position `r` generated by a `Wire` source.
Integral of (mu0 I / 4pi) * dl / |r - r'|.
"""
function solve(::VectorPotential, source::Wire{T}, r::SVector{3, T}) where {T}
    A = @SVector zeros(T, 3)
    points = source.points
    I = source.current

    for i in 1:(length(points) - 1)
        r1 = points[i]
        r2 = points[i + 1]

        # Segment vector
        l = r2 - r1
        L = norm(l)
        L < 1.0e-20 && continue
        u = l / L # Unit vector along wire

        # Simpler form using r1 and r2 distances:
        d1 = norm(r - r1)
        d2 = norm(r - r2)

        # The integral of 1/|r-r'| along the segment is:
        # ln( (d1 + d2 + L) / (d1 + d2 - L) )

        val = log((d1 + d2 + L) / (d1 + d2 - L))

        A += (μ0_4π * I * val) * u
    end

    return A
end

"""
    solve(solver::VectorPotential, source::Dipole, r) where T

Compute vector potential A for a magnetic dipole.
A = (mu0 / 4pi) * (m x r) / r^3
"""
function solve(::VectorPotential, source::Dipole{T}, r::SVector{3, T}) where {T}
    r_mag = norm(r)
    if r_mag < 1.0e-10
        return @SVector zeros(T, 3)
    else
        return (μ0_4π / r_mag^3) * cross(source.M, r)
    end
end

"""
    solve(solver::VectorPotential, source::CurrentLoop, r::AbstractVector)

Compute vector potential A for a circular current loop.
"""
function solve(::VectorPotential, loop::CurrentLoop{T}, r::SVector{3, T}) where {T}
    # Using the same coordinate transformation as in getB_loop
    (; radius, current, center, normal) = loop
    n_hat = normal

    # Relative position
    r_rel = r - center

    # Local coordinates
    z_local = dot(r_rel, n_hat)
    rho_vec = r_rel - z_local * n_hat
    rho = norm(rho_vec)

    if rho < 1.0e-10 # On-axis
        # A is zero on axis for a loop due to symmetry
        return @SVector zeros(T, 3)
    end

    # A_phi calculation using Elliptic integrals
    # A_phi = (mu0 I / pi k) * sqrt(R/rho) * [ (1 - k^2/2)*K - E ]
    # where k^2 = 4 R rho / ((R+rho)^2 + z^2)

    R = radius
    denom_sq = (R + rho)^2 + z_local^2
    k_sq = 4 * R * rho / denom_sq
    k = sqrt(k_sq)

    K_val = ellipk(k_sq)
    E_val = ellipe(k_sq)

    prefactor = (μ₀ * current) / (π * k) * sqrt(R / rho)

    A_phi = prefactor * ((1 - k_sq / 2) * K_val - E_val)

    # Transform A_phi * phi_hat back to Cartesian
    # phi_hat = (-sin phi, cos phi, 0) in local basis where x_local is along rho_vec
    # Actually, rho_vec defines the radial direction. phi_vec is n_hat x rho_hat

    rho_hat = rho_vec / rho
    phi_hat = cross(n_hat, rho_hat)

    return A_phi * phi_hat
end

# Helpers to support arbitrary location input (open BC, default)
function solve(solver::VectorPotential, source::Wire{T}, r) where {T}
    return solve(solver, source, SVector{3, T}(r))
end
function solve(solver::VectorPotential, source::Dipole{T}, r) where {T}
    return solve(solver, source, SVector{3, T}(r))
end
function solve(solver::VectorPotential, source::CurrentLoop{T}, r) where {T}
    return solve(solver, source, SVector{3, T}(r))
end

# ConductingWall: sum direct + image potential
function solve(
        solver::VectorPotential{ConductingWall}, source::Wire{T},
        r::SVector{3, T}
    ) where {T}
    A_direct = solve(VectorPotential(), source, r)
    img = image_source(source, solver.bc)
    A_image = solve(VectorPotential(), img, r)
    return A_direct + A_image
end
function solve(solver::VectorPotential{ConductingWall}, source::Wire{T}, r) where {T}
    return solve(solver, source, SVector{3, T}(r))
end

# Make struct callable
function (solver::VectorPotential)(source, r)
    return solve(solver, source, r)
end

"""
    PoissonSolver{ALG} <: AbstractSolver

Grid-based solver for the magnetostatic vector potential equation
∇²**A** = −μ₀ **J** on a uniform Cartesian grid with homogeneous Dirichlet
boundary conditions (`A = 0` on all domain faces).

Each Cartesian component is solved independently with the same 7-point
finite-difference Laplacian matrix via `LinearSolve.jl`.  Pass any
`LinearSolve` algorithm as `alg`; the default is `KrylovJL_CG()`.

# Fields
- `xs`, `ys`, `zs`: grid node positions as `AbstractRange` objects.
- `alg`: `LinearSolve` algorithm (e.g. `KrylovJL_CG()`,
  `KLUFactorization()`, `UMFPACKFactorization()`).

# Example
```julia
xs = range(-1.0, 1.0; length = 32)
ys = range(-1.0, 1.0; length = 32)
zs = range(-0.5, 0.5; length = 16)
solver = PoissonSolver(xs, ys, zs)                 # default: CG
solver_direct = PoissonSolver(xs, ys, zs; alg = KLUFactorization())
A = solve(solver, J_grid)  # J_grid :: (3,Nx,Ny,Nz)
```
"""
struct PoissonSolver{ALG} <: AbstractSolver
    xs::AbstractRange
    ys::AbstractRange
    zs::AbstractRange
    alg::ALG
end

PoissonSolver(xs, ys, zs; alg = KrylovJL_CG()) = PoissonSolver(xs, ys, zs, alg)

# Build the (N×N) sparse matrix for -∇² with 7-point central differences.
# Supports anisotropic spacing (dx, dy, dz). Boundary nodes carry identity
# rows (Dirichlet: A = 0).
function _build_laplacian_3d(Nx::Int, Ny::Int, Nz::Int, dx::Real, dy::Real, dz::Real)
    N = Nx * Ny * Nz
    inv_dx2 = inv(dx)^2
    inv_dy2 = inv(dy)^2
    inv_dz2 = inv(dz)^2
    diag_val = 2(inv_dx2 + inv_dy2 + inv_dz2)

    rows = Int[]
    cols = Int[]
    vals = Float64[]

    function idx(i, j, k)
        return (k - 1) * (Nx * Ny) + (j - 1) * Nx + i
    end

    function is_boundary(i, j, k)
        return i == 1 || i == Nx || j == 1 || j == Ny || k == 1 || k == Nz
    end

    for k in 1:Nz, j in 1:Ny, i in 1:Nx
        row = idx(i, j, k)
        if is_boundary(i, j, k)
            push!(rows, row); push!(cols, row); push!(vals, 1.0)
        else
            push!(rows, row); push!(cols, row); push!(vals, diag_val)
            for (di, dj, dk, coeff) in (
                    (-1, 0, 0, inv_dx2), (1, 0, 0, inv_dx2),
                    (0, -1, 0, inv_dy2), (0, 1, 0, inv_dy2),
                    (0, 0, -1, inv_dz2), (0, 0, 1, inv_dz2),
                )
                push!(rows, row)
                push!(cols, idx(i + di, j + dj, k + dk))
                push!(vals, -coeff)
            end
        end
    end

    return sparse(rows, cols, vals, N, N)
end

"""
    solve(solver::PoissonSolver, J::AbstractArray{T,4}) where T

Solve ∇²**A** = −μ₀ **J** on the grid defined by `solver`.
Grid spacings are derived automatically from `solver.xs`, `solver.ys`, `solver.zs`,
supporting anisotropic grids (dx ≠ dy ≠ dz).

# Arguments
- `J`: 4-D array of size `(3, Nx, Ny, Nz)` (same convention as `FFTSolver`).

# Returns
- `A`: 4-D array of size `(3, Nx, Ny, Nz)` with the vector potential.
"""
function solve(solver::PoissonSolver, J::AbstractArray{T, 4}) where {T}
    @assert size(J, 1) == 3 "First dimension of J must be 3"
    _, Nx, Ny, Nz = size(J)
    N = Nx * Ny * Nz
    dx, dy, dz = step(solver.xs), step(solver.ys), step(solver.zs)

    L = _build_laplacian_3d(Nx, Ny, Nz, dx, dy, dz)
    A = zeros(T, 3, Nx, Ny, Nz)

    for c in 1:3
        b = fill(zero(T), N)
        for k in 1:Nz, j in 1:Ny, i in 1:Nx
            # Boundary nodes: b stays zero (Dirichlet)
            if i > 1 && i < Nx && j > 1 && j < Ny && k > 1 && k < Nz
                row = (k - 1) * (Nx * Ny) + (j - 1) * Nx + i
                b[row] = μ₀ * J[c, i, j, k]
            end
        end
        prob = LinearProblem(L, b)
        sol = LinearSolve.solve(prob, solver.alg)
        A[c, :, :, :] = reshape(sol.u, Nx, Ny, Nz)
    end

    return A
end
